version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to DockerHub...
      - docker login -u $dockerhub_username -p $dockerhub_password
      - REPOSITORY_URI=$ecr_uri
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t server .
      - docker tag server server:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --no-include-email --region us-east-1)
      - echo Pushing the Docker images...
      - docker push server
      - docker push server:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"nginx","imageUri":"%s"}]' server:$IMAGE_TAG > imagedefinitions.json
artifacts:
    files: imagedefinitions.json
